web:
  build: .
  dockerfile: ./infra/app.dockerfile
  environment:
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: foobarbaz
  links:
    - db
  ports:
    - "10000:3000"
  volumes:
    - ./out:/var/app/out
db:
  image: postgres:9.4
  environment:
    POSTGRES_USER: test_user
    POSTGRES_PASSWORD: foobarbaz
  volumes:
    - ./db:/docker-entrypoint-initdb.d
